### ISSUE TITLE
ansibleにおける特殊タグ処理の修正（nbck完全適用後）

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#11]
- master-slaveタグの動作の削除
　slaveタグでmasterタグの内容を参照する処理を実施せず、master-slaveタグは無視する
- wifiタグの動作
　NBに設定されたままにuntaggedとtaggedにVLANを設定する

**Comment by mi2428** [comment]
- Ansible側でMaster/Slaveやる必要ない（NBに忠実に入れてくれればいい）
- Wi-Fiタグに関してはすでに修正済みなので関係ない

**Comment by mi2428** [comment]
ゴールデンウィーク前でよろしくです

**Comment by kitaguch** [comment]
nbck側で制御できていることが確認できているので、Ansible側の旧実装が残っていなければcloseでOK。
旧実装：
- master-slaveタグでslave側を上書き
- wifiタグでWi-Fi設定をインタフェースに投入
確認お願いします。

**Comment by mi2428** [comment]
いまのAnsibleは愚直にNBを入れるだけなので↑はやっていない。
※ VLAN空っぽのAccess Modeインターフェイスはいちいちコケてるとめんどくさいので無視する例外を入れた。それくらい
