### ISSUE TITLE
PoE SWタグの定義を削除

### ISSUE THREAD

**Issue by mi2428** [yamaoka-kitaguchi-lab/tn4-player#16]
- Tn3のころの手で入れたVLANが消えない
- Tn4のVLANは追加されてる
- PoE SWタグは廃止されたのでコードから削除

**Comment by mi2428** [comment]
これが直らないと #11 できない

**Comment by kitaguch** [comment]
本件の修正に合わせて、PoE SW タグの実装を削除してください。NB からは削除しました。

**Comment by mi2428** [comment]
- PoEタグ：PoE有効化で使ってる
- PoE SWタグ：これはもういらないので消す（BPDUタグで吸収）

**Comment by mi2428** [comment]
すでに対応済みっぽいのでクローズ。ソースコード中にPoE SWタグで分岐する処理が見つからなかった
