### ISSUE TITLE
edgeにおけるuplink以外のデフォルトフィルタ設定の不備

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#17]
set interfaces {{ interface }} unit 0 family ethernet-switching storm-control "storm3M"
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list CDP
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list CDP
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list BPDU
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list BPDU
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list DEFAULT
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list DEFAULT
これらの設定が、ae11などのPoEスイッチ接続ポートに設定されない。

{% if prop.physical and not prop.lag_member %} 物理ポートに限定されている模様

**Comment by mi2428** [comment]
```
ils/network/common/netconf.py\", line 126, in parse_rpc_error\nansible.module_utils.connection.ConnectionError: b'error: logical unit is not allowed on aggregated links\\nerror: logical unit is not allowed on aggregated links\\nerror: configuration check-out failed'\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

**Comment by mi2428** [comment]
これどうすればいいかなー
