### ISSUE TITLE
BRANCH VLAN追加・削除時処理の自動化

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#25]
支線VLAN（VLAN Role = BRANCH）は、coreがVRRPによるGWとなる運用。
新規作成および削除処理を最小化する仕組みを構築する。

**新規作成時**
1. NBでVLANを新規作成（VLAN Role = BRANCH）
　- GWとなるキャンパスに応じてIRB-O or IRB-Sタグを設定
2. 当該VLANに割り当てるIPアドレスプレフィックスを作成
　- VRRP Maste, VRRP Backup, VRRP VIPのタグをIPアドレスに設定
3. nbckを実行することで以下をNBに作成
　- IRB-O/IRB-Sタグを元に、coreにIRB IFを作成し、VRRP設定を投入
　- coreのIFにVRRP関連のIPアドレスをそれぞれ設定
4. ansibleにてVRRPタグによるIRB IFの作成と設定を実機投入
　- 対象はcoreスイッチ
*1~3を別スクリプトで実現することも想定
*ansibleではIRB IFに対しての追加・削除処理の追加実装が必要

**Comment by kitaguch** [comment]
支線VLANに対するRIPおよびRA(現状利用なし)の設定もansibleに必要

**Comment by mi2428** [comment]
VLAN999を参考に他も同じ構成になるようにnbckで自動投入したい

**Comment by mi2428** [comment]
- ステップ1-2のVLANIDとIPアドレス採番（タグ付与）は人間がやってNBに登録する。ステップ3でnbckがIRBインターフェイス作成とVRRP設定をやる
- ステップ4でNBに従いAnsibleで設定投入する。VRRPのConfigテンプレートなど

@kitaguch 
- 投入するConfigのサンプル

**Comment by kitaguch** [comment]
仕様作成しました。

1. NBでVLANを新規作成 (VLAN Role = BRANCH)
  - GWとなるキャンパスに応じてIRB-O or IRB-Sタグを設定
    - 例 VLAN 999, tag IRB-O, VLAN-O
2. NBで当該VLANに割り当てるIPアドレスプレフィックスを作成 (IP Role = BRANCH)
  - 当該VLANの"Prefixes"にIPプレフィックスを設定
    - 例 131.112.126.0/26
         2403:4440:3:999::/64
  - VRRP Master, VRRP Backup, VRRP VIPのタグをIPアドレスに設定
    - 例 131.112.126.42/26 VRRP VIP
         131.112.126.46/26 VRRP Backup
         131.112.126.47/26 VRRP Master
         2403:4440:3:999::a/64 VRRP VIP
         2403:4440:3:999::6/64 VRRP Backup
         2403:4440:3:999::7/64 VRRP Master
3. nbckを実行することで以下をNBに作成
  - VRRPタグからFHRP Groupを作成
    - 例 FHRP Group IDはVIDの1/10の値(990~999まで同じ99という意味)
          FHRP Groups:
            Group: 99         *INT(<VID>/10)
            Name: 999         *<VID>を入れる(Netbox 3.4系で実装)
            Description: noc-life-o *VLANのdescription 
            Virtual IP Addresses:
              IP Assress: 131.112.126.42/26
              IP Assress: 2403:4440:3:999::/64
  - IRB-O/IRB-Sタグを元に、coreにIRB IFを作成し、VRRP設定を紐付け
    - 例 IRB-Oなので、core-honkan (Master), core-gsic (Backup)に
         irb.<VID> IFを作成し、IPアドレスを紐付け
          Name: irb.999
          Type: Virtual
          MTU: 1500
          802.1Q Mode: Access
          untagged VLAN: 999
          IP Address:
            IP Assress: 131.112.126.47/26 (core-honkan)
            IP Assress: 131.112.126.46/26 (core-gsic)
            IP Assress: 2403:4440:3:999::7/64 (core-honkan)
            IP Assress: 2403:4440:3:999::6/64 (core-gsic)
            Role: VRRP
          FHRP Groups:
            Group: 99
            Protocol: VRRPv3
            Virtual IPs: 131.112.126.42/26
            Virtual IPs: 2403:4440:3:999::a/64
            Priority: 1 (core-honkan)
            Priority: 0 (core-gsic)
  - ae0 (拠点core間VRRP用MCLAG IF) に当該VLANを追加
    - 例 ae0に999を追加
  - VLAN-OかつVLAN-Sの場合、ae1 (キャンパス間MCLAG IF) に当該VLANを追加
    - 例 VLAN-Oのみなので追加しない
4. ansibleにてVRRPタグによるIRB IFの作成と設定を実機投入
  - VLAN作成
    [共通]
```
    set vlans v999_noc-life-o vlan-id 999
    set interfaces ae0 unit 0 family ethernet-switching vlan members 999
```
  - IRB IFの作成とVRRP設定 *VRRP Master側からCommitする必要あり
    [core-honkan]
```
    set interface irb unit 999 apply-groups vrrp-master
    set interface irb unit 999 description noc-life-o
    set interface irb unit 999 family inet mtu 1500
    set interface irb unit 999 family inet address 131.112.126.47/26 vrrp-group 99
    set interface irb unit 999 family inet address 131.112.126.47/26 virtual-address 131.112.126.42
    set interface irb unit 999 family inet6 mtu 1500
    set interface irb unit 999 family inet6 address 2403:4440:3:999::7/64 vrrp-group 99
    set interface irb unit 999 family inet6 address 2403:4440:3:999::7/64 virtual-address 2403:4440:3:999::a
```
    [core-gsic]
```
    set interface irb unit 999 apply-groups vrrp-backup
    set interface irb unit 999 description noc-life-o
    set interface irb unit 999 family inet mtu 1500
    set interface irb unit 999 family inet address 131.112.126.46/26 vrrp-group 99
    set interface irb unit 999 family inet address 131.112.126.46/26 virtual-address 131.112.126.42
    set interface irb unit 999 family inet6 address 2403:4440:3:999::6/64 vrrp-group 99
    set interface irb unit 999 family inet6 address 2403:4440:3:999::6/64 virtual-address 2403:4440:3:999::a
```
    [共通]
`    set vlans v999_noc-life-o l3-interface irb.999`
  - RIPの設定
    [共通]
`    set protocols rip group shisen neighbor irb.999`

**Comment by kitaguch** [comment]
VRRP設定では以下のグループ設定が存在していることが前提
```
VRRP-COMMON {
    interfaces {
        <*> {
            unit <*> {
                family inet {
                    address <*> {
                        vrrp-group <*> {
                            preempt {
                                hold-time 600;
                            }
                            accept-data;
                            authentication-type md5;
                            authentication-key "$9$T3/ArlM-VYO1-bw2GUqmf5Q3n/CAuOQF"; ## SECRET-DATA
                        }
                    }
                }
                family inet6 {
                    address <2403:4440:*/64> {
                        vrrp-inet6-group <*> {
                            virtual-link-local-address fe80::a;
                            preempt {   
                                hold-time 600;
                            }
                            accept-data;
                        }
                    }
                    address fe80::7/64 {
                        vrrp-inet6-group <*> {
                            virtual-link-local-address fe80::a;
                            preempt {
                                hold-time 600;
                            }
                            accept-data;
                        }
                    }
                }
            }
        }
    }
}
VRRP-MASTER {
    interfaces {
        <*> {
            unit <*> {
                family inet {
                    address <*> {
                        vrrp-group <*> {
                            apply-groups VRRP-COMMON;
                            priority 200;
                        }
                    }
                }
                family inet6 {
                    address <2403:4440:*/64> {
                        vrrp-inet6-group <*> {
                            apply-groups VRRP-COMMON;
                            priority 200;
                        }
                    }
                    address fe80::7/64 {
                        vrrp-inet6-group <*> {
                            apply-groups VRRP-COMMON;
                            priority 200;
                        }
                    }
                }
            }
        }
    }
}
VRRP-BACKUP {
    interfaces {
        <*> {
            unit <*> {
                family inet {
                    address <*> {
                        vrrp-group <*> {
                            apply-groups VRRP-COMMON;
                            priority 150;
                        }
                    }
                }
                family inet6 {
                    address <2403:4440:*/64> {
                        vrrp-inet6-group <*> {
                            apply-groups VRRP-COMMON;
                            priority 150;
                        }
                    }
                    address fe80::7/64 {
                        vrrp-inet6-group <*> {
                            apply-groups VRRP-COMMON;
                            priority 150;
                        }
                    }
                }
            }
        }
    }
}
```

**Comment by kitaguch** [comment]
タグの制御仕様も更新
https://docs.google.com/spreadsheets/d/1F88mVO5Qo0lxmAqMoHjY_FvEIMfbBqJkjqSxsicRbZk/edit?usp=share_link

**Comment by mi2428** [comment]
## branch.BranchVlan.exec_add()
1. VLANが存在するか確認→しなければfail
2. Prefixを作成→重複する場合はfail
3.

**Comment by mi2428** [comment]
こっちで管理。クローズ
https://github.com/yamaoka-kitaguchi-lab/tn4-player/issues/80

**Comment by mi2428** [comment]
https://github.com/yamaoka-kitaguchi-lab/tn4-player/issues/25#issuecomment-1432902158
configが間違っている

```
set interfaces irb unit 999 apply-groups VRRP-MASTER
set interfaces irb unit 999 description noc-life-o
set interfaces irb unit 999 family inet mtu 1500
set interfaces irb unit 999 family inet address 131.112.126.47/26 vrrp-group 99 virtual-address 131.112.126.42
set interfaces irb unit 999 family inet6 address 2403:4440:3:999::7/64 vrrp-inet6-group 99 virtual-inet6-address 2403:4440:3:999::a
```
