### ISSUE TITLE
NB v3.2系対応によるSpeed設定用タグの廃止

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#26]
v3.2.2に変更したことで、IFにSpeed設定が可能になった。
これを受け、Speed設定処理をansibleに追加し、Speed設定タグを廃止する。

削除するタグ：speed-10m, speed-100m, speed-1g

(参考) 現在当該タグが設定されているIF
100nen: ge-0/0/6 (speed-100m)
ishikawa8: ge-0/0/0 (speed-10m)

**Comment by mi2428** [comment]
こうなる
http://netbox.m.noc.titech.ac.jp:8000/api/dcim/interfaces/28423/

```
    "mac_address": null,
    "speed": 100000,
    "duplex": null,
```

**Comment by mi2428** [comment]
> (参考) 現在当該タグが設定されているIF
100nen: ge-0/0/6 (speed-100m)
ishikawa8: ge-0/0/0 (speed-10m)

- netbox02に設定されている→　　100nen: ge-0/0/6 (speed-100m)
- netbox02に設定されていない→　ishikawa8: ge-0/0/0 (speed-10m)
