### ISSUE TITLE
nbckにおけるVLANグループの確認

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#29]
VLAN変換を想定してVLANグループがTitanet以外にも存在しているため、nbckでその違いをチェックする必要がある。
現在のnbckの機能はTitanetグループのVLANだけが対象なので、Titanetグループ以外のVLANがcore, edgeに設定されていた場合にTitanetグループに修正したい。

**Comment by mi2428** [comment]
修正しない
- Titanetグループ以外のVLANがEdge/Coreインターフェイスに設定されていたら warning で跳ねる

**Comment by kitaguch** [comment]
「Titanetグループ以外のVLANがEdge/Coreインターフェイスに設定されていたら warning で跳ねる」
この実装ができていればcloseで。

**Comment by mi2428** [comment]
実装した気持ちになったので、一旦クローズ。Titanetグループ以外のVLANが設定されているインターフェイスを発見した場合、警告のみを表示し、VLAN削除などの自動修復は行わない
