### ISSUE TITLE
シャットダウンツール

### ISSUE THREAD

**Issue by mi2428** [yamaoka-kitaguchi-lab/tn4-player#30]
- Ansibleで落とす準備をする。実行するのは北口先生
- 機器エリア識別できるようにする。エリアごとのデプロイをサポートする必要

**Comment by mi2428** [comment]
またデスゲームするらしい。ただ一応将来のために停電ツールは作っておこうと思う

**Comment by kitaguch** [comment]
8/13, 14の法定点検において、UPSを使い切って落ちたedgeはすべて問題なく立ち上がった模様。
NOCでは、頭のいいUPSが配置されることになった際に、シャットダウンの仕組みを利用する予定。

**Comment by mi2428** [comment]
tn4 shutdownコマンドで実現予定。このIssueはクローズ
