### ISSUE TITLE
disableポートのdescription設定

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#46]
disableポートでの`description ""`は不要。

```
{% if interface.description %}
set interfaces {{ interface.name }} description {{ interface.description }}
{% endif %}
```

mtuの処理と同様で良さそう。

**Comment by mi2428** [comment]
mtuもdescriptionも指定されていない場合は no を入れて消す。
現状mtuは9000→未指定になった場合に9000が残るのでダメ
https://github.com/yamaoka-kitaguchi-lab/tn4-player/blob/1b3075521d600620270c8a705f179c573a684ae7/project/roles/juniper/templates/include/edge/set-interfaces.j2#L5-L7
