### ISSUE TITLE
ShutdownインタフェースにおけるVLAN設定がNB設定と異なる

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#49]
NB上で、イベント用VLANや一部の支線VLANでインタフェースを予約する意味合いで、VLAN設定を削除せずにdisableしているケースがある。以前の実装では、VLAN設定が入っていてshutdownとなっていたが、現状の実装では、disableでインタフェースの設定が全て消える実装になっているように見える。
enable状態で設定が反映されるので問題なさそうだが、基本的にNBの設定のまま反映しておくほうがトラブルが少ないと考えるので、以前の実装（disableでもNBの設定を反映）に戻してほしい。

**Comment by mi2428** [comment]
#21の通りにフィルタに関しては削除。VLANは残す
