### ISSUE TITLE
BPDUフィルタ投入条件が間違っている

### ISSUE THREAD

**Issue by mi2428** [yamaoka-kitaguchi-lab/tn4-player#5]
**tn4-player/roles/juniper/templates/interface_edge.cfg.j2**：こちら確認しましたが、BPDUフィルタのデフォルト設定が消えています。すべでのIFにデフォルトでフィルタを投入するので、BPDUタグを見ているif文のみの削除になります。BPDUタグ は core でのみ作用することになるので、interface_core.cfg.j2 はOKのようです。

デフォルトですべてのIFにBPDUフィルタを適用するということです。
```
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list BPDU
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list BPDU
```

これらが、interface_edge.cfg.j2 から消えていませんか？
よくみると、以下もuplinkだけに設定されている？
```
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list DEFAULT
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list DEFAULT
```

**Comment by kitaguch** [comment]
フィルタ(storm-control含)に関する設定をここにも整理しておきます。
edge：すべてのIFに以下の設定(デフォルト設定)を実施
set interfaces {{ interface }} unit 0 family ethernet-switching storm-control "storm3M"
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list CDP
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list CDP
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list BPDU
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list BPDU
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list DEFAULT
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list DEFAULT
 uplink タグがあるIFには上記設定を実施しない(抑制する)
core：BPDUタグのあるIFにのみ以下の設定を実施
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list BPDU
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list BPDU
set interfaces {{ interface }} unit 0 family ethernet-switching filter input-list DEFAULT
set interfaces {{ interface }} unit 0 family ethernet-switching filter output-list DEFAULT
※DEFAULTルールが最後にないとすべての通信が落ちる

edge では、uplink 以外、CDP, BPDUを禁止し、storm-control も厳しめに 3Mbps に抑える設定を入れています。
core では、特定の IF のみ、BPDU を禁止したいとの要望で、現在は protect タグを設定したうえで、実機に投入しています。改修後、BPDUタグでの対応に移行する予定。

**Comment by mi2428** [comment]
#12 と関連するのでクローズ
