### ISSUE TITLE
廃止作業における運用ミスの修正機能

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#51]
edgeのポート利用廃止処理時に、以下の状態となるインタフェースが散見される。
- interface-mode accessの削除忘れ
- disableし忘れ

本件に関して、nbckにて以下の機能を追加したい。
- vlanメンバなし かつ description空の場合、ステータスをdisableとしてtagやinterface-modeなどの設定も削除
- 上記でPoE tagが設定されていた場合、poeポート設定も併せて削除

なお、イベント用インタフェースでは、vlanメンバなしでdisableとする運用があるので、これはdescriptionを設定することで回避する。

**Comment by kitaguch** [comment]
イベント用インタフェースをdescriptionの有無で判断せず、専用のタグを設けることにする。
インタフェース利用破棄時の運用ミス回避のため、Obsoletedタグを新設する。nbckにてObsoletedタグが設定されたインタフェースを初期化（各設定を削除してdisable）する。

上記以外の中途半端なインタフェース設定に対して：
- vlanメンバなし かつ description空
- interface-modeなしでenable
- インタフェース設定なしでPoEタグなどが設定
このような状態はnbckで初期化状態にしたい。

**Comment by kitaguch** [comment]
設定を保存しつつ、enable/disableを実施するIFを定義する「Keepタグ」
廃止時処理をAPIにて実施するIFを定義する「Obsoletedタグ」
これらの定義を仕様に追加した。
https://docs.google.com/spreadsheets/d/1F88mVO5Qo0lxmAqMoHjY_FvEIMfbBqJkjqSxsicRbZk/edit#gid=0

「Keepタグ」のないIFにて、中途半端な設定（先に挙げた3つのケース）のものはnbckで初期化状態にする。

**Comment by mi2428** [comment]
KeepとObsoletedが同時指定されていたら何もしない。警告を表示するだけ

**Comment by mi2428** [comment]
実装した気持ちになった。一旦クローズ
