### ISSUE TITLE
キャンパス範囲指定のための--regions範囲指定の追加と--areas範囲指定の改訂

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#55]
キャンパス毎のデプロイを実現するための--regions範囲指定を追加したい。
また、--areas指定はedgeのみを対象に変更したい。

**Comment by mi2428** [comment]
> キャンパス毎のデプロイを実現するための--regions範囲指定を追加したい。
--areas suzukake とか --areas tamachi すれば↑の期待通りに動作する。実装不要

> また、--areas指定はedgeのみを対象に変更したい。
--include-core を追加してデフォルトはedgeのみにする？（だいぶ前にこのIssueのやり取りSlackでやった気がするけど忘れた。2/10に確認）

**Comment by mi2428** [comment]
--areas suzukake --roles edge_sw でOK
