### ISSUE TITLE
MCLAG-Slaveタグの名称変更

### ISSUE THREAD

**Issue by kitaguch** [yamaoka-kitaguchi-lab/tn4-player#82]
MCLAG-Slaveタグの名称をMCLAG-Backupに変更したい。
優先度はかなり低い

**Comment by mi2428** [comment]
タグをはじめとするすべてのNetBox Objectには、UI上表示されるDisplay Nameと、URLなどで使われる省略名のSlugの2種類があります。tn4コマンドは内部的にSlugを使ってオブジェクトを参照しているので（Slugを変更しないなら）Display Nameをどういじっても動作には影響しません。

http://netbox.m.noc.titech.ac.jp:8000/extras/tags/22/
の場合は、Display Nameが【MCLAG Slave (Core)】でSlugが【mclag-master-core】です。

Slugを変更したい場合は↓のファイルを修正してください。
言うまでもなく変更していいのは右側の文字列で、左側の変数名は触らないでください。
https://github.com/yamaoka-kitaguchi-lab/tn4-player/blob/main/lib/tn4/netbox/slug.py#L34
